### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by lyjmry** [fidlabs/Open-Data-Pathway#102]
### Data Owner Name

tianchi ali

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://tianchi.aliyun.com/dataset/

### Social Media Handle

Hi fil

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

1000TiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

1000TiB

### On-chain address for first allocation

f142ljf6i6zz5wjze47jcfexu6eptwkadzvwhsq5a

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
About me: I have joined the Filecoin ecosystem since 2019, and have been active in the community since the second half of 2020, and have contributed to filecoin Greater China by providing resource information reports, resource docking, etc.

about project:The data comes from Alibaba Cloud's Tianchi Data, a large open dataset.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
This is a public data set from Tianchi。
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Alibaba Cloud
```

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I will fully communicate with the storage providers, including downloading the data to my local hard disk for offline transactions. If bandwidth resources are sufficient due to long distances, the storage provider will download it from AWS, using including but not limited to boost
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
N/A
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
N/A
```

### Please share a sample of the data

```text
https://tianchi.aliyun.com/dataset/148818
https://tianchi.aliyun.com/dataset/93339
https://tianchi.aliyun.com/dataset/83983
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Never

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How did you find your storage providers

Slack, Others

### If you answered "Others" in the previous question, what is the tool or platform you used

```text
Wechat
```

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03215853  US
f03218576 US
f03220172 Singapore
f03220176 HONGKONG
.......
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by lyjmry** [comment]
> This client address has also applied for datacap at [http://github.com/NDLABS-Leo/Allocator-Pathway-ND-CLOUD/issues/37](https://github.com/NDLABS-Leo/Allocator-Pathway-ND-CLOUD/issues/37) - Please use a new, distinct client address for this application, so that usage can be clearly understood as relating to this application.

This Allocator does not support public dataset applications, so I have disabled it.

**Comment by martplo** [comment]
@lyjmry 
Thank you, I have following questions on your application. I'm sure you're familiar with some of those:
- The links you provided contain significantly less than 100TiB of data. What exactly does the full dataset contain? We'd like to browse all the data that you're planning to store. 
- In the data preparation section, you mentioned AWS. Could you clarify what this has to do with downloading data from Alibaba Cloud? What the process is if it requires AWS as well?
- More storage regions will be needed than China and Singapore. Please, provide other regions too.
- How the data will be transformed into deals for filecoin?
- How when we sample your deals will we be able to confirm that it has come from the dataset?

**Comment by lyjmry** [comment]
Hi @martplo  Sorry, I found that there was a problem with my script for counting file sizes. I will recalculate and if there is no target size, I will close the application.  thank you
