### ISSUE TITLE
[DataCap Application] w3s - web3.storage

### ISSUE THREAD

**Issue by heyjay44** [fidlabs/Open-Data-Pathway#18]
### Data Owner Name

w3s and the users of our tools

### Data Owner Country/Region

United States

### Data Owner Industry

Web3 / Crypto

### Website

https://web3.storage/

### Social Media Handle

https://twitter.com/web3storage

### Social Media Type

Twitter

### What is your role related to the dataset

Data onramp entity that provides data onboarding services to multiple clients

### Total amount of DataCap being requested

2 PiB - the current pace of DataCap usage is 130 TiB/2 weeks

### Expected size of single dataset (one copy)

600 TiB and growing 

### Number of replicas to store

10

### Weekly allocation of DataCap requested

250 TiB

### On-chain address for first allocation

TBD

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
DAG House - now w3s - was founded in 2021 as a team inside Protocol Labs to develop tools to make it easy for developers and end users to host content addressed data and store the data on Filecoin. Since then our two flagship products, NFT.Storage (Internet Archive of NFTs) and Web3.Storage (developer storage platform) are used by many prominent projects and companies in Web3 and outside of it. NFT.Storage has recently spun out into its own corporate entity.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
This project is associated with Protocol Labs. Projects have plans for independence.
```

### Describe the data being stored onto Filecoin

```text
User uploads that meet or adhere to web3.storage's terms of service (https://web3.storage/docs/terms/).
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
User uploads (generally for their web3 apps)
```

### If you are a data preparer. What is your location (Country/Region)

None

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
The goal is to be able to use the Filecoin copies as the only available copies on the network (rather than also storing the data on centralized infra), which requires things like retrieval to have high performance and global availability. As a result, some parts of the dataset have already been stored but not to the replication limit with other Datacap apps (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1838, https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2110, https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2192).
```

### Please share a sample of the data

```text
This platform serves all different kinds of media, including images, files, and videos. Some examples:
https://ipfs.io/ipfs/bafybeid5jpdqzlb4tqsd6peoa7qstoxat3ovsg62wutyp4gnzqbqsggfsq
https://ipfs.io/ipfs/bafybeihity6bx24npzvvkzopjbat25ekefjwmnshe7rvldy72dxngzf644
https://ipfs.io/ipfs/bafybeicvcevx3ktiqjsfwnjguu4lnzejlhgb35brayuod5xdtn7demfdhe
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How did you find your storage providers

Others

### If you answered "Others" in the previous question, what is the tool or platform you used

```text
We plan to use Spade for SP selection and deal execution. Spade is managed by the Akave team, which is currently affiliated with Protocol Labs and supports storage client to SP matching based on requirements like geography, size, retrievability, etc.
```

### Please list the provider IDs and location of the storage providers you will be working with.

```text
web3.storage's Filecoin deals are brokered through Spade, which handles SP selection.
```

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
We plan to use Spade for deal execution to onboard data to Filecoin. Spade is being managed by the Akave team. 

Spade was initially servicing Slingshot deals and was referred to as the Evergreen Dealer.
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by kevzak** [comment]
Create a new application when ready @heyjay44
