### ISSUE TITLE
[DataCap Application] <<Re-forecast>> 

### ISSUE THREAD

**Issue by Laycuicui** [fidlabs/Open-Data-Pathway#19]
### Data Owner Name

NOAA

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

http://www.noaa.gov/

### Social Media Handle

https://twitter.com/NOAA

### Social Media Type

Other

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

390TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1000TiB

### On-chain address for first allocation

f1wmz2bbj3xu7e23daodegr45bxrnz2373wftcifq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NOAA is an agency that enriches life through science. Our reach goes from the surface of the sun to the depths of the ocean floor as we work to keep the public informed of the changing environment around them. I'm a DP with some experience of distribute data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
NOAA has generated a multi-decadal reanalysis and reforecast data set to accompany the next-generation version of its ensemble prediction system, the Global Ensemble Forecast System, version 12 (GEFSv12).
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-gefs-reforecast/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03074583  
f03074586   
f03074587   
f03074589   
f03074592
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Laycuicui** [comment]
<img width="1434" alt="image" src="https://github.com/fidlabs/Open-Data-Pathway/assets/149811699/35e5ff1b-0a20-4374-bb69-785d72075d8a">

1. verified.

2. Because the first round amount is only 500TiB, the plan is to find these 5 SPs to work with first.
f03074583  Fly  Japan
f03074586  Datastone  HK
f03074587  Hanku  Korea
f03074589  Xing  HK
f03074592  HKblockchain  USA

We will continue to look for new SPs. The SPs we are currently communicating with are f03028318, f02363305, f02182802.

**Comment by kevzak** [comment]
Because the first round amount is only 500TiB, the plan is to find these 5 SPs to work with first.

First round is 500TiB? I'm confused. You are applying 5PiB with dataset size 390TiB. Please clarify. Also please show proof of dataset size.

**Comment by jacktree7** [comment]
![image](https://github.com/fidlabs/Open-Data-Pathway/assets/116623999/c4f38774-68f5-4806-a37f-99380d8e66ec)

![image](https://github.com/fidlabs/Open-Data-Pathway/assets/116623999/9f7d239c-bf25-4344-bae5-ce99a04d568a)

![image](https://github.com/fidlabs/Open-Data-Pathway/assets/116623999/5c6aa094-35f4-44bb-886c-93ccf80ca4ec)

Based on the storage barrels, it can be assumed that there are at least 400TiB of real data. I plan to send 8x copies, each for 390TiB raw data. Since there is a conversion rate between the raw data size and Datacap consumption size, each copy would require around 650TiB Datacap, with a total amount of  5PiB Datacap. Also first round is 500TiB.

**Comment by Laycuicui** [comment]
![image](https://github.com/fidlabs/Open-Data-Pathway/assets/149811699/88211c6d-ab81-4596-9e28-4cd479b5a7ce)

![image](https://github.com/fidlabs/Open-Data-Pathway/assets/149811699/9f022828-1820-4131-b3f8-43a75ccc2f35)

![image](https://github.com/fidlabs/Open-Data-Pathway/assets/149811699/3512559c-b357-4b8d-8c4d-eda50c669bd0)


Based on the storage barrels, it can be assumed that there are at least 400TiB of real data. I plan to send 8x copies, each for 390TiB raw data. Since there is a conversion rate between the raw data size and Datacap consumption size, each copy would require around 650TiB Datacap, with a total amount of 5PiB Datacap. Also first round is 500TiB.

**Comment by kevzak** [comment]
Hello @Laycuicui of the miner IDs you shared: 
f03074583 Fly Japan
f03074586 Datastone HK
f03074587 Hanku Korea
f03074589 Xing HK
f03074592 HKblockchain USA

We'll need some better representation of the entity and location. This list shows five IDs that are likely in the same datacenter. Need a better detail of who is storing which copies. 

Also all five have 0% retrieval or are unavailable on Spark Dashboard. SPs you choose need to make retrievals available or you will not be able to receive DataCap from this allocator. Please advise


![image](https://github.com/fidlabs/Open-Data-Pathway/assets/102751751/6041f6af-cf3d-42e0-882c-8560bf034714)

**Comment by Laycuicui** [comment]
@kevzak Sorry for the late reply.
1. Each entity will be storing a backup, of course this is just the first round, as more and more quota is issued, more SPs will be entered for storage.
2. Spark retrieval, SPs feedback that the Spark team is collaborating on all DC paths including V4 and V5, currently only collaborating on LDN in V4 mode, so for new storage in V5, the retrieval rate is 0. But rest assured, SPs are fully compliant. You can follow the follow-up report.

**Comment by kevzak** [comment]
@Laycuicui please complete this form with more detailed client and SP information so I can review: https://form.jotform.com/240786057753667
