### ISSUE TITLE
[DataCap Application] <test for lotus > <2024-06-17T16:39:29.400Z>

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/Open-Data-Pathway#35]
## Version
2024-06-17T16:39:29.400Z

## DataCap Applicant
@filipagr

## Data Owner Name
test for lotus

## Data Owner Country/Region
Other

## Website
test.com

## Social Media Handle
test for lotus

## Social Media Type
Other

## What is your role related to the dataset
Other

## Total amount of DataCap being requested
100 GiB

## Expected size of single dataset (one copy)
100 GiB

## Number of replicas to store
2

## Weekly allocation of DataCap
0 GiB

## On-chain address for first allocation
f1hzzjom4d3bm2fexplwjfcsuztbfnxmoih7hmbzq

## Data Type of Application
Public, Open Dataset (Research/Non-Profit)

## Share a brief history of your project and organization
test for lotus

## Is this project associated with other projects/ecosystem stakeholders?
No

## If answered yes, what are the other projects/ecosystem stakeholders
test for lotus

## Where was the data currently stored in this dataset sourced from
Other

## Please share a sample of the data
test for lotus

## Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

## What is the expected retrieval frequency for this data
Never

## For how long do you plan to keep this dataset stored on Filecoin
Less than 1 year

## In which geographies do you plan on making storage deals
Europe

## How will you be distributing your data to storage providers
Others

## How did you find your storage providers
Others

## Please list the provider IDs and location of the storage providers you will be working with.
test for lotus

## Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by kevzak** [comment]
Giving 100GiB for lotus testing for Filecoin Foundation
