### ISSUE TITLE
[DataCap Application] <K12 International Education Platform> - < datastorage>

### ISSUE THREAD

**Issue by 1613557499** [fidlabs/Open-Data-Pathway#37]
### Data Owner Name

K12 International Education Platform

### Data Owner Country/Region

Singapore

### Data Owner Industry

Education & Training

### Website

http://www.topschools.cn/index?_l=en

### Social Media Handle

顶思

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

512TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1dvulxgyfvnv3fqwjpelfhictonbf3vytdgao4xy

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
TopSchools was founded on August 28, 2016.  As the resource aggregation platform of K12 international Education, TopSchools is committed to supporting the sustainable development of the international school market through community communication, data research, teacher training and talent recruitment.  Topschools is a close partner of international schools and international education institutions.  Provides industry with information on international education policies, operations, investments, schools, and people.  Organized various online and offline activities, cooperated with various examination bureaus, global top universities, research institutions, embassies and consulates, and provided services and support for more than 600 schools across the country;  We are linked to thousands of quality school service providers around the world to provide a variety of solutions for schools.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Our data is very large, mainly stored all kinds of courses of teaching videos, materials, documents.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We plan to cooperate and negotiate with professionals to ensure the safety and reliability of data, and achieve short-term or long-term effective storage to ensure the integrity of data
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We have previously applied for 1p data, that data is only a small part of our total data, the company's development is stable, our data is always growing, storage costs are also increasing, the need for filecoin network support, for the development of the traditional Internet industry to promote.
```

### Please share a sample of the data

```text
https://pan.baidu.com/s/1vOQ-h6lCCLvCXAY_PtsP1A?pwd=6jt9 
https://pan.baidu.com/s/1CbRHk1E-tiXULoJIgLawMw?pwd=iapx 
https://pan.baidu.com/s/1_qSCseiHfUPyXFumfgvsLQ?pwd=fgis
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Filmine, Big Data Exchange, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02850067
fo2830476
fo2941888
fo2950965
fo2830451
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Droplet client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by kevzak** [comment]
Hello @1613557499 please clarify who are the SPs you are involved with:

**Comment by kevzak** [comment]
Hello @1613557499 this application will require a business check to confirm your connection to K12 International Education Platform and their data. There are two options:

- complete a third party KYB check via https://efilplus.synaps.me/signup (cost is $100) and they will check business license and complete KYC
- complete a virtual zoom call with me, the data owner, and the lead Storage Provider. 

Let me know

**Comment by 1613557499** [comment]
> Hello @1613557499 this application will require a business check to confirm your connection to K12 International Education Platform and their data. There are two options:
> 
> * complete a third party KYB check via https://efilplus.synaps.me/signup (cost is $100) and they will check business license and complete KYC
> * complete a virtual zoom call with me, the data owner, and the lead Storage Provider.
> 
> Let me know

This was not required before, is it necessary? Why do I need this? What are the contents and questions of the call if I choose the second method? Can you tell me? What I understand is that we can call and give you a recording file, right? Still don't understand why it is so complicated and wait for your reply, thank you

**Comment by kevzak** [comment]
Yes, this is an unknown user to me. I would need proof that @1613557499 is somehow associated with this dataset and that this company is in fact a registered legit company. 

If you prefer, first fill this form with client info https://form.jotform.com/240786057753667 and I can review and contact client directly for more information.

Also, please complete a KYC sanctions check via https://filplus.storage/kyc you can login with this github and get verified. Thank you.

**Comment by 1613557499** [comment]
> Yes, this is an unknown user to me. I would need proof that @1613557499 is somehow associated with this dataset and that this company is in fact a registered legit company.
> 
> If you prefer, first fill this form with client info https://form.jotform.com/240786057753667 and I can review and contact client directly for more information.
> 
> Also, please complete a KYC sanctions check via https://filplus.storage/kyc you can login with this github and get verified. Thank you.

![image](https://github.com/fidlabs/Open-Data-Pathway/assets/86406225/6e5e7157-4f0f-436d-b6f5-3f9db98fc339)
I have submitted the application, and the remaining sp is still following up the chat

**Comment by kevzak** [comment]
I sent an email @1613557499 please confirm

**Comment by 1613557499** [comment]
> I sent an email @1613557499 please confirm

Thank you for your reply. I just got the message that the recipient has replied，Could you approve my application？

**Comment by kevzak** [comment]
> > I sent an email @1613557499 please confirm
> 
> Thank you for your reply. I just got the message that the recipient has replied，Could you approve my application？

They did not provide any information that I'm asking for. 

To approve this application we need to see:
-review the dataset and size
-confirm ownership (proof of employment, employer signoff, sharing the business license) - we can setup a call as I mentioned.
-and validate storage of the data by the client/applicant is approved and a contract with the SP(s) is in place.

So far I have only been provided 3 SP IDs. None are setup for retrievals. 
f01970622  HongKong
f0832131 YangZhou
f01146045 Singapore

**Comment by kevzak** [comment]
You can see all the pathway guidelines here. https://github.com/fidlabs/Open-Data-Pathway/blob/main/README.md

I'm not trying to make this hard on you, just need to follow the guidelines.

**Comment by 1613557499** [comment]
<img width="526" alt="image" src="https://github.com/fidlabs/Open-Data-Pathway/assets/86406225/eabd6752-abb7-4d4c-9cd9-b4a5b8c3da5f">

f03143698，HongKong
f03143705，Shanghai
f0870354，Singapore
f01989372，HongKong

hello,
1. I have tried my best to meet your requirements. I got a message that the materials have been sent to kevin@fidl.tech from the email address you confirmed before, please check it.
2, in addition, the recent packaging has been reduced, our sp is also unstable, the above new home sp are communicated with the intention to cooperate, and continue to strive for cooperation with other sp，If my dc application is approved, it can be used immediately
3. I see that there is a kyc about gitcoin which I have already operated
Looking forward to your reply, thank you

**Comment by 1613557499** [comment]
> KYC has been requested. Please complete KYC at https://kyc.allocator.tech/?owner=fidlabs&repo=Open-Data-Pathway&client=f1dvulxgyfvnv3fqwjpelfhictonbf3vytdgao4xy&issue=37

My account only has 2.99 points, which is all I can get for all the apps I tried

**Comment by kevzak** [comment]
OK. Then the other available KYC option is:

1. go to [filplus.storage](https://filplus.storage/)
2. Log in with your github account (top right corner)
3. Click on your Profile Icon (Next to a bell icon)
4. Choose "Confirm Identity"
5. Scroll to about middle of the page and follow an external link to togggle third party check.
6. You will need a mobile phone, and an ID.

**Comment by 1613557499** [comment]
> OK. Then the other available KYC option is:
> 
> 1. go to [filplus.storage](https://filplus.storage/)
> 2. Log in with your github account (top right corner)
> 3. Click on your Profile Icon (Next to a bell icon)
> 4. Choose "Confirm Identity"
> 5. Scroll to about middle of the page and follow an external link to togggle third party check.
> 6. You will need a mobile phone, and an ID.

![f94915e1015a0869634463ed252bd74](https://github.com/fidlabs/Open-Data-Pathway/assets/86406225/983e3bb7-66b6-4a32-a040-d0b36a2ac239)
Why is this? I've tried every app on my phone that's available, and it's all the same

**Comment by 1613557499** [comment]
> OK. Then the other available KYC option is:
> 
> 1. go to [filplus.storage](https://filplus.storage/)
> 2. Log in with your github account (top right corner)
> 3. Click on your Profile Icon (Next to a bell icon)
> 4. Choose "Confirm Identity"
> 5. Scroll to about middle of the page and follow an external link to togggle third party check.
> 6. You will need a mobile phone, and an ID.

<img width="545" alt="image" src="https://github.com/fidlabs/Open-Data-Pathway/assets/86406225/3f677fb2-a4f0-43da-a142-c50518ce864f">
@kevzak Hi，I've gone through a very difficult process of verification

**Comment by kevzak** [comment]
OK great, thank you @1613557499 . 

Please confirm SPs with retrievals that will be used for this dataset and we can move forward with a first allocation

**Comment by 1613557499** [comment]
f03143698，HongKong
f03143705，Shanghai
f0870354，Singapore
f01989372，HongKong

@kevzak  We have communicated with sps and will consider these first in the first round

**Comment by kevzak** [comment]
These SPs do not enable retrievals, the IDs are not available on Spark Dashboard: https://spacemeridian.grafana.net/public-dashboards/32c03ae0d89748e3b08e0f08121caa14?orgId=1

**Comment by 1613557499** [comment]
> These SPs do not enable retrievals, the IDs are not available on Spark Dashboard: https://spacemeridian.grafana.net/public-dashboards/32c03ae0d89748e3b08e0f08121caa14?orgId=1
> 
> can you explain why?


<img width="370" alt="image" src="https://github.com/fidlabs/Open-Data-Pathway/assets/86406225/4ee21a34-319d-4550-a0ae-5c0978b7c897">

@kevzak I have been looking for sp to understand, their newly opened sp for encapsulation, hope to get the first round of support, let's look forward to the next process and results

**Comment by kevzak** [comment]
@1613557499 I can allocate 50TiBs as a first allocation. Let's ensure SPs match and retrievals are enabled. Thank you

**Comment by kevzak** [comment]
Also can you please include documentation on how the data is transformed into deals for filecoin?

when a deal is sampled for verification, how will we be able to confirm that it is part of this dataset? (how is is chunked into car files?)

**Comment by 1613557499** [comment]
> Also can you please include documentation on how the data is transformed into deals for filecoin?
> 
> when a deal is sampled for verification, how will we be able to confirm that it is part of this dataset? (how is is chunked into car files?)

I don't quite understand this, I asked sp, he is normal packaging

**Comment by 1613557499** [comment]
checker:manualTrigger

**Comment by 1613557499** [comment]
> No active deals found for this client.

Why is there no active trading yet? How do I start the next round of applications

**Comment by filecoin-watchdog** [comment]
> > Also can you please include documentation on how the data is transformed into deals for filecoin?
> > when a deal is sampled for verification, how will we be able to confirm that it is part of this dataset? (how is is chunked into car files?)
> 
> I don't quite understand this, I asked sp, he is normal packaging

@willscott

**Comment by filecoin-watchdog** [comment]
> > No active deals found for this client.
> 
> Why is there no active trading yet? How do I start the next round of applications

You can see deals here @1613557499 https://datacapstats.io/clients/f03147079/ddo-deals - DDO deals do not show on CID report yet

**Comment by kevzak** [comment]
@1613557499 

We have successfully seen datasets be prepared for filecoin, ranging from internet archive, to wikipedia, to the chain itself. You can either store the metadata structure above the individual file chunks as is done by e.g. web3 storage, or you can have a separate well-advertised metadata layer via e.g. a website.

We want to see how a client could be able to make use of this dataset. Can you share details?

this could be a client script for how to iterate through / process over the data
this could be a web site allowing browsing / identification of specific pieces of data from the dataset as stored
this could be identification of clients making use of the data

**Comment by 1613557499** [comment]
> @1613557499
> 
> 我们已经成功看到为 filecoin 准备的数据集，从互联网档案到维基百科，再到链本身。您可以像 web3 存储那样将元数据结构存储在各个文件块之上，也可以通过网站等方式拥有一个单独的、广为人知的元数据层。
> 
> 我们想看看客户如何利用这个数据集。您能分享详细信息吗？
> 
> 这可能是一个客户端脚本，用于描述如何迭代/处理数据； 这可能是一个网站，允许浏览/识别存储的数据集中的特定数据； 这可能是对使用数据的客户端的识别

We only have less than 50T in the package, so there's no customer search yet

**Comment by kevzak** [comment]
> > No active deals found for this client.
> 
> Why is there no active trading yet? How do I start the next round of applications

Hi @1613557499 https://datacapstats.io/clients?filter=f1dvulxgyfvnv3fqwjpelfhictonbf3vytdgao4xy shows the deal usage thus far.

**Comment by 1613557499** [comment]
checker:manualTrigger

**Comment by 1613557499** [comment]
@kevzak there is a transaction record, why still can't open a new round of applications, I have already sealed more than 75%.

**Comment by kevzak** [comment]
@1613557499 this comment https://github.com/fidlabs/Open-Data-Pathway/issues/37#issuecomment-2271074326 is not asking for transaction record.  We are asking how the client can retrieve the data. Please provide detail

**Comment by 1613557499** [comment]
> @1613557499 this comment [#37 (comment)](https://github.com/fidlabs/Open-Data-Pathway/issues/37#issuecomment-2271074326) is not asking for transaction record. We are asking how the client can retrieve the data. Please provide detail

@kevzak Thank you for your reply. The current version is that you don't need to care about transaction records, so manual triggering at work is normal, right?
As for how the client can retrieve data, we can obtain the CID content through the command line, and then submit it to the front-end for query, but the process is a little complicated, we need time to study, the final result is that we can query the content on our official website

**Comment by 1613557499** [comment]
@kevzak I see changes in the information, but there is no hint of the next step, what do I need to do next

**Comment by kevzak** [comment]
@1613557499 normally after the client uses 75% of DataCap allocation, I complete my diligence checks.

**Comment by 1613557499** [comment]
> @1613557499 normally after the client uses 75% of DataCap allocation, I complete my diligence checks.

More than 75% of the data I configured has been encapsulated. I haven't seen any further instructions, and I haven't signed the quota for the next round. Do I still need to find a notary? Or how much longer do I have to wait?

**Comment by kevzak** [comment]
@1613557499 can you confirm the SP miner IDs that received deals in this initial tranche?

**Comment by 1613557499** [comment]
@kevzak Hello, why do I still have 50T in this round? According to the rules, I should have 5% of the total allocation in this round

**Comment by kevzak** [comment]
My guidelines are for trusted clients with reputation. As a client you have [one previous application](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2283) that wasn't great per the community. 

For this dataset, I don't yet have any trust. You've onboarded 50Tib with one SP. This SP does not make retrievals available. And there is no understanding of how the client can retrieve this data (documentation).

I've giving you a second small round of DataCap to prove out your plan.

**Comment by 1613557499** [comment]
> My guidelines are for trusted clients with reputation. As a client you have [one previous application](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2283) that wasn't great per the community.
> 
> For this dataset, I don't yet have any trust. You've onboarded 50Tib with one SP. This SP does not make retrievals available. And there is no understanding of how the client can retrieve this data (documentation).
> 
> I've giving you a second small round of DataCap to prove out your plan.


@kevzak  hi，
SP does not provide a search function, I have a question, how can there be a search function, I need to tell sp how to operate. We are all the initial try of this track, for some questions are still exploring, please help to answer them, I hope to make the ecology of filecoin better, thank you

**Comment by kevzak** [comment]
Docs for Spark retrieval tool are here: https://filspark.com/

**Comment by 1613557499** [comment]
> Docs for Spark retrieval tool are here: https://filspark.com/

I first ask if I need to download the spark program, and then I don't have to worry about anything, why my search rate is still not making progress

**Comment by 1613557499** [comment]
<img width="988" alt="image" src="https://github.com/user-attachments/assets/e51afc28-5b19-47cf-8d40-305c24f81241">
@kevzak  Hello, my quota is gone, sp is configuring retrieval, to be honest, we are exploring how to make the data retrieval successful, hoping to get the allocation of the next round and ensure the success of data retrieval

**Comment by 1613557499** [comment]
> Docs for Spark retrieval tool are here: https://filspark.com/

@kevzakI haven't received your reply. What is the situation

**Comment by willscott** [comment]
checker:manualTrigger

**Comment by willscott** [comment]
So what's going on here?

* you say you store 4 replicas, but all data has been stored on one SP
* You have no retrieval on that SP
* 10% of the data overlaps with 'DigitalEarth Africa' which should be a totally different dataset.

you need the SP to start providing retrieval. once it does, we can check to see if this is actually the dataset you have claimed it is

**Comment by 1613557499** [comment]
> 那么这里发生了什么？
> 
> * 你说你存储了 4 个副本，但所有数据都存储在一个 SP 上
> * 您无法检索该 SP
> * 10％的数据与“DigitalEarth Africa”重叠，这应该是一个完全不同的数据集。
> 
> 您需要 SP 开始提供检索。一旦开始，我们就可以检查这是否确实是您所声称的数据集

<img width="812" alt="image" src="https://github.com/user-attachments/assets/2a20e357-b4de-4dba-b553-80b94dbccf28">

@willscott Hello, sp and I are still in the exploratory stage, and we haven't released a lot of DC quota in the early stage. We are working on the data retrieval function, and the total allocation is 100T, which is a small amount. Thank you for reminding us that we will replace sp.

**Comment by willscott** [comment]
you were given a second allocation to make changes.
you have not

at this point, as an allocator, we see your client behavior as not in line with our guidelines.

once we can validate retrieval and correctness of the initial 100tb, we can consider allocation of additional datacap if it will be used to replicate to other SPs.

**Comment by 1613557499** [comment]
> you were given a second allocation to make changes. you have not
> 
> at this point, as an allocator, we see your client behavior as not in line with our guidelines.
> 
> once we can validate retrieval and correctness of the initial 100tb, we can consider allocation of additional datacap if it will be used to replicate to other SPs.

@willscott  I am a novice to participate in this process for the first time, my sp tells me that I can retrieve the data, what should I do?

**Comment by willscott** [comment]
The report was run in the comment an hour ago and shows no retrieval is possible as of today.

**Comment by 1613557499** [comment]
> 该报告是在一小时前在评论中运行的，但截至今天仍无法检索。

Is the search to download the spark program in the packaging machine, and then the program automatically search? What's the procedure, please advise, thank you very much

**Comment by willscott** [comment]
checker:manualTrigger

**Comment by 1613557499** [comment]
> ## DataCap and CID Checker Report Summary[1](#user-content-fn-1-a3e094f24624f29e5a097ae422e63529)
> ### Storage Provider Distribution
> ⚠️ 1 storage providers sealed more than 90% of total datacap - [f03143698](https://filfox.info/en/address/f03143698): 100.00%
> 
> ⚠️ All storage providers are located in the same region.
> 
> ### Deal Data Replication
> ✔️ Data replication looks healthy.
> 
> ### Deal Data Shared with other Clients[2](#user-content-fn-3-a3e094f24624f29e5a097ae422e63529)
> ⚠️ CID sharing has been observed. (Top 3)
> 
> * 190.44 TiB - [f02884258](https://filfox.info/en/address/f02884258) - [DigitalEarth Africa](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2289)
> 
> ### Full report
> Click [here](https://check.allocator.tech/report/fidlabs/Open-Data-Pathway/issues/37/1725975477974.md) to view the CID Checker report.
> 
> ## Footnotes
> 1. To manually trigger this report, add a comment with text `checker:manualTrigger` [↩](#user-content-fnref-1-a3e094f24624f29e5a097ae422e63529)
> 2. To manually trigger this report with deals from other related addresses, add a comment with text `checker:manualTrigger <other_address_1> <other_address_2> ...` [↩](#user-content-fnref-3-a3e094f24624f29e5a097ae422e63529)

**Comment by 1613557499** [comment]
> checker:manualTrigger
@willscott  @kevzak 
“It is estimated that my deal is related to the latest DDO (direct deal).  does spark search support DDO orders?”
The above is the news of my sp, can you help to answer it?

**Comment by willscott** [comment]
* you say you store 4 replicas, but all data has been stored on one SP
* You have no retrieval on that SP
* 10% of the data overlaps with 'DigitalEarth Africa' which should be a totally different dataset.
*

**Comment by 1613557499** [comment]
> * you say you store 4 replicas, but all data has been stored on one SP
> * You have no retrieval on that SP
> * 10% of the data overlaps with 'DigitalEarth Africa' which should be a totally different dataset.

1. The first round of my application is 512T, and I think it is no problem to allocate one sp every 100T
2. My SP uses the latest DOO, may I ask if this is the reason why it cannot be retrieved?
3. Is this non-repetitive data set good or bad? How can I correct it

@willscott  What I need is guidance to correct my problem step by step, please

**Comment by willscott** [comment]
Sorry, you've demonstrated this isn't your data set at this point and you aren't acting as the client.

**Comment by nicelove666** [comment]
https://github.com/fidlabs/Open-Data-Pathway/issues/37
https://github.com/fidlabs/Open-Data-Pathway/issues/76
K12 has applied here twice, and willscott of PL has closed your application.
We think that any company can only apply for DC once.
However, K12 also applied multiple times during the v3-v4.
Sorry, we can not support you for the time being.
<img width="1225" alt="WX20240920-131936@2x" src="https://github.com/user-attachments/assets/0a9e4854-931a-43b5-8ddd-a3df206d2dd2">
