### ISSUE TITLE
[DataCap Application] <ER > <2024-07-02T09:30:06.302Z>

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/Open-Data-Pathway#45]
### Version
2024-07-02T09:30:06.302Z

### DataCap Applicant
@tina

### Data Owner Name
ER

### Data Owner Country/Region
Construction, Property & Real Estate

### Website
DFGDG@DGDF.COM

### Social Media Handle
DDGD

### Social Media Type
Twitter

### What is your role related to the dataset
Dataset Owner

### Total amount of DataCap being requested
2PiB

### Expected size of single dataset (one copy)
23TiB

### Number of replicas to store
4

### Weekly allocation of DataCap
2PiB

### On-chain address for first allocation
f1jcqmubrauzuq324orcmomau6wrmx466cypznm23

### Data Type of Application
Private Commercial/Enterprise

### Share a brief history of your project and organization
xxfgsfgsfgs

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
sgsfgsgsrrtstsrts

### Where was the data currently stored in this dataset sourced from
AWS Cloud

### If you are a data preparer. What is your location (Country/Region)
Argentina

### Please share a sample of the data
fhdfhdhdhdgh

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Confirm

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
1 to 1.5 years

### In which geographies do you plan on making storage deals
Asia other than Greater China

### How will you be distributing your data to storage providers
IPFS

### How did you find your storage providers
Partners

### Please list the provider IDs and location of the storage providers you will be working with.
zdfxvxcvxcvxcvxcv

### How do you plan to make deals to your storage providers
Singularity

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by kevzak** [comment]
Hello @tina thank you for applying. Please complete the KYC humanity check requested above. Alternatively, you can go to filplus.storage and verify your GitHub account.

**Comment by kevzak** [comment]
This is a private dataset?

**Comment by kevzak** [comment]
closing until we hear from client
