### ISSUE TITLE
[DataCap Application] <DataFortress> - <Health-WHO-GHO24>

### ISSUE THREAD

**Issue by techgood123** [fidlabs/Open-Data-Pathway#47]
### Data Owner Name

DataFortress-Health-WHO-GHO24

### Data Owner Country/Region

Switzerland

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.who.int/

### Social Media Handle

https://www.who.int/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

2PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1nppxhqeyeafhac6xrqbxnqz3rzdye252r2l4iba

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
TechToolbox is a technology services company that specializes in providing comprehensive solutions to our clients. We have a deep understanding of FILECOIN and excel at utilizing various tools to meet our clients' needs.

Our team consists of technical experts with extensive experience in the field. We recognize the significance of technology in modern business and are committed to delivering innovative and efficient solutions to our clients.

In the realm of FILECOIN, we are expert partners. We comprehend the working principles, potential, and application scenarios of FILECOIN, and we possess the expertise to optimize your FILECOIN experience using a wide range of tools and technologies.

Our services encompass a broad range of areas, including technology consulting, system integration, software development, and data analysis. Whether you are a startup or a well-established enterprise, we can provide customized solutions tailored to your specific requirements.

We prioritize our clients' success and work closely with them to ensure that our solutions help them achieve their business objectives. We are not just technology providers; we are collaborative partners dedicated to delivering excellence in technical services.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Providing better health information around the world is a core goal of the World Health Organization, which publicly releases their global health data through the Global Health Observatory (GHO). The GHO is a portal for understanding and analyzing the health situation and major issues.
The various datasets are organized by themes such as mortality, health systems, communicable and noncommunicable diseases, medicines and vaccines, health risks, etc. WHO health statistics are the best source of global health information and are also used by the Centers for Disease Control and Prevention in the United States.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### Please share a sample of the data

```text
http://www.who.int/gho/maternal_health/reproductive_health/en/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Filmine

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02956383   Hong Kong
f03148950    Hong Kong
f03035686   Shenzhen, Guangdong, CN
f03068013   Hong Kong
f03136267   Hong Kong
f03144077   Hong Kong
```

### How do you plan to make deals to your storage providers

Boost client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by kevzak** [comment]
@techgood123 please provide SP Entities associated with each SP

f02956383   Hong Kong
f03148950    Hong Kong
f03035686   Shenzhen, Guangdong, CN
f03068013   Hong Kong
f03136267   Hong Kong
f03144077   Hong Kong

**Comment by kevzak** [comment]
Also - please complete a KYC check above using link. 

If not, the other KYC option is:


- go to [filplus.storage](https://filplus.storage/)
- Log in with your github account (top right corner)
- Click on your Profile Icon (Next to a bell icon)
- Choose "Confirm Identity"
- Scroll to about middle of the page and follow an external link to togggle third party check.
- You will need a mobile phone, and an ID.

**Comment by techgood123** [comment]
Hey, we have completed KYC, have you received https://filplus.storage/kyc

We confirmed that these SPs can be retrieved via Spark.

**Comment by techgood123** [comment]
Individual    f02956383    Hong Kong
CoffeeCloud  f0314407   Hong Kong
CoffeeCloud  f03136267   Hong Kong
ShenSuanCloud  f03035686   Nanchang, Jiangxi, CN
Lucky Star     f03068013   Hong Kong
Lucky Star     f03148950   Now in Hong Kong, will move to Singapore later

**Comment by techgood123** [comment]
hope to get your help

**Comment by willscott** [comment]
Hi, you link to
http://www.who.int/gho/maternal_health/reproductive_health/en/

I don't see any link from there to AWS, which you say is the source for the data.
Searching AWS open data sets does not bring up any listings for WHO maternal or reproductive health data sets.

We're looking in particular for the data and the data preparation process that you are intending to take, so that we will be able to verify that the data set that is put on chain through this application actually matches what is being proposed.

There is currently not sufficient specificity to identify what data exactly is being proposed to be uploaded here.
