### ISSUE TITLE
[DataCap Application] Radio telescope——National Radio Astronomy Observatory

### ISSUE THREAD

**Issue by techgood123** [fidlabs/Open-Data-Pathway#60]
### Data Owner Name

National Radio Astronomy Observatory

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://data.nrao.edu/portal/#/

### Social Media Handle

https://data.nrao.edu/portal/#/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1z4utkyc4xxwfwc3pmupvrgdbp4pjj6yiw3y2opi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
TechToolbox is a technology services company that specializes in providing comprehensive solutions to our clients. We have a deep understanding of FILECOIN and excel at utilizing various tools to meet our clients' needs.

Our team consists of technical experts with extensive experience in the field. We recognize the significance of technology in modern business and are committed to delivering innovative and efficient solutions to our clients.

In the realm of FILECOIN, we are expert partners. We comprehend the working principles, potential, and application scenarios of FILECOIN, and we possess the expertise to optimize your FILECOIN experience using a wide range of tools and technologies.

Our services encompass a broad range of areas, including technology consulting, system integration, software development, and data analysis. Whether you are a startup or a well-established enterprise, we can provide customized solutions tailored to your specific requirements.

We prioritize our clients' success and work closely with them to ensure that our solutions help them achieve their business objectives. We are not just technology providers; we are collaborative partners dedicated to delivering excellence in technical services.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Founded in 1956, NRAO provides the most advanced radio telescope facilities and information to the international scientific community. Currently, https://data.nrao.edu/portal/#/ has stored 4.3PB of data.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
We counted the data on this website, a total of 500,800 pieces of information, with a total capacity of 4.2P。

https://docs.google.com/spreadsheets/d/1F26TunJBid_6SqMYOQscSpm3793y4xYu/edit?usp=share_link&ouid=109823390606932719085&rtpof=true&sd=true
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives

### How did you find your storage providers

Slack, Filmine

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03068013-HK
f03035686-GuangDong
f01926635-SiChuang
f01999119-SiChuang
f03136267-HK
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by willscott** [comment]
This dataset appears to have already been added to filecoin in 15 separate instances https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+NRAO&type=issues 

Please justify why more copies are valuable to the filecoin network?

**Comment by techgood123** [comment]
Sorry, we did not consider the problem of replicas, we will close this application and continue to look for new dataset applications
