### ISSUE TITLE
[DataCap Application] <Lucky Red Cat Limited > <2024-08-27T12:49:48.243Z>

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/Open-Data-Pathway#72]
### Version
2024-08-27T12:49:48.243Z

### DataCap Applicant
@smagdali

### Data Owner Name
Lucky Red Cat Limited

### Data Owner Country/Region
IT & Technology Services

### Website
www.whitelabel.org

### Social Media Handle
@smagdali

### Social Media Type
Twitter

### What is your role related to the dataset
Dataset Owner

### Total amount of DataCap being requested
10 PiB

### Expected size of single dataset (one copy)
10 PiB

### Number of replicas to store
10

### Weekly allocation of DataCap requested:
10 PiB

### On-chain address for first allocation
f14zia5uzkehczplx2fcujcd3isav2sh5rhxjiwki

### Data Type of Application
Private Commercial/Enterprise

### Identifier
testbotstef

### Share a brief history of your project and organization
We came here to eat dogfood

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
holiday snaps

### Where was the data currently stored in this dataset sourced from
AWS Cloud

### If you are a data preparer. What is your location (Country/Region)
United Kingdom

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
on toast, with mayonnaise

### If you are not preparing the data, who will prepare the data? (Provide name and business)
I'll make Robert do it

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
I don't know

### Please share a sample of the data
Are you asking for a url? you should say so. I can't paste it in here.

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Confirm

### If you chose not to confirm, what was the reason
I thought if I said no, you'd deny me. 

### What is the expected retrieval frequency for this data
Weekly

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Antarctica

### How will you be distributing your data to storage providers
HTTP or FTP server

### How did you find your storage providers
Big Data Exchange

### Please list the provider IDs and location of the storage providers you will be working with.
comma separated, but what if I don't know then yet?

### How do you plan to make deals to your storage providers
Boost client

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by willscott** [comment]
> Are you asking for a url? you should say so. I can't paste it in here.
yes. this path is meant for public data sets, so we should be able to independently get pointed to the data set.

> on toast, with mayonnaise
We won't consider this fully until a full answer is provided here.

**Comment by willscott** [comment]
as you did is fine.
