### ISSUE TITLE
[DataCap Application] <顶思> - <datastorage>

### ISSUE THREAD

**Issue by 1613557499** [fidlabs/Open-Data-Pathway#76]
### Data Owner Name

顶思

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

http://www.topschools.cn/index

### Social Media Handle

顶思

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

1PiB

### Expected size of single dataset (one copy)

512TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1twvalxpcgzaw3pnca4hfvzeyl542xd43piz2w3y

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
TopSchools was founded on August 28, 2016.  As the resource aggregation platform of K12 international Education, TopSchools is committed to supporting the sustainable development of the international school market through community communication, data research, teacher training and talent recruitment.  Topschools is a close partner of international schools and international education institutions.  Provides industry with information on international education policies, operations, investments, schools, and people.  Organized various online and offline activities, cooperated with various examination bureaus, global top universities, research institutions, embassies and consulates, and provided services and support for more than 600 schools across the country;  We are linked to thousands of quality school service providers around the world to provide a variety of solutions for schools.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Our data is very large, mainly stored all kinds of courses of teaching videos, materials, documents.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We plan to cooperate and negotiate with professionals to ensure the safety and reliability of data, and achieve short-term or long-term effective storage to ensure the integrity of data
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We have previously applied for 1p data, that data is only a small part of our total data, the company's development is stable, our data is always growing, storage costs are also increasing, the need for filecoin network support, for the development of the traditional Internet industry to promote.
```

### Please share a sample of the data

```text
https://pan.baidu.com/s/13wL5KTvY-JjgpezbqxJVIA?pwd=hgxv 
https://pan.baidu.com/s/1uWAOYMjv5OP_BA9k-QH1eQ?pwd=w97f
https://pan.baidu.com/s/1VSUjDCzAdZLdK5ESLC1fBA?pwd=qd56
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, South America, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer, Venus built-in data transfer

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03143698，HongKong
f03143705，Shanghai
f0870354，Singapore
f01989372，HongKong
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Droplet client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by 1613557499** [comment]
@willscott @kevzak Can you take a look?

**Comment by willscott** [comment]
How is this different from https://github.com/fidlabs/Open-Data-Pathway/issues/37

**Comment by 1613557499** [comment]
> How is this different from #37
Changed strategy. As you can see we're more mature
