### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by Atonia12** [fidlabs/Open-Data-Pathway#90]
### Data Owner Name

1

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Life Science / Healthcare

### Website

1

### Social Media Handle

1

### Social Media Type

Slack

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

100TiB

### Expected size of single dataset (one copy)

32G

### Number of replicas to store

4

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1oe3xl5llyiu42t6ewyfhen3efoa7a7xwk23455d

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
1
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
1
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you answered "Other" in the previous question, enter the details here

```text
1
```

### If you are a data preparer. What is your location (Country/Region)

None

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
1
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
1
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
1
```

### Please share a sample of the data

```text
1
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
1
```

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How did you find your storage providers

Filmine

### If you answered "Others" in the previous question, what is the tool or platform you used

```text
1
```

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1
```

### How do you plan to make deals to your storage providers

Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
1
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by martplo** [comment]
@Atonia12 Could you explain why you opened this issue?
