### ISSUE TITLE
[DataCap Application] WWM - KVideo and Image

### ISSUE THREAD

**Issue by scvpark** [fidlabs/Open-Data-Pathway#94]
### Data Owner Name

WWM

### Data Owner Country/Region

Korea, Republic of

### Data Owner Industry

IT & Technology Services

### Website

https://deny.co.kr

### Social Media Handle

@CM_JH

### Social Media Type

Slack

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

1PiB

### Expected size of single dataset (one copy)

10TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

30TiB

### On-chain address for first allocation

f1aflacds2zsw3sranghltvfccp7onzargonr7r3i

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Crawling and storing Korean videos and images, and imaging old videos to preserve them.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Images of various videos such as Korean entertainment, drama, Kpop, K Dance, etc
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

Korea, Republic of

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Crawling, FFMPEG
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1UlDq0fdbuuzBCBzcKpE1u0rYWVfwMEQ8
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1. f02943119, Chungju, North Chungcheong Province, Korea
2. f02860778, Gwangju, South Jeolla Province, Korea
Other SP from European, Australian, and Japanese countries will be found in slack and added to it.
```

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by martplo** [comment]
@scvpark I'm confused. Why did you apply [here](https://github.com/fidlabs/Enterprise-Data-Pathway/issues/76) as well?

**Comment by scvpark** [comment]
@martplo 
I checked the 2 forms before applying for DC allocation, and I thought one of the 2 was not working.
Let's close this issue, and we'll proceed here at https://github.com/fidlabs/Enterprise-Data-Pathway/issues/76 .
