### ISSUE TITLE
[DataCap Application] <  武汉斗鱼网络科技有限公司 > <2024-10-29T01:34:28.057Z>

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/Open-Data-Pathway#95]
### Version
2024-10-29T01:34:28.057Z

### DataCap Applicant
@dengxy-111

### Data Owner Name
  武汉斗鱼网络科技有限公司

### Data Owner Country/Region
Information, Media & Telecommunications

### Website
www.douyu.com

### Social Media Handle
Dengxixi888

### Social Media Type
Slack

### What is your role related to the dataset
Data Preparer

### Total amount of DataCap being requested
1PiB

### Expected size of single dataset (one copy)
125TiB

### Number of replicas to store
8

### Weekly allocation of DataCap requested
50TiB

### On-chain address for first allocation
f1jume6m3vnglk5rp7h2ofqamadtecrfgcw7qaa5y

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Identifier
f03234833

### Share a brief history of your project and organization
Douyu is the earliest game live streaming platform in China and is still very popular today. The live streaming videos of the anchors have a large storage capacity. Currently, only Douyu itself keeps a copy, so we want to save as much as possible in fil. If some videos are lost, we can get them as a backup. We are also preparing to make a front-end web page to support retrieval.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
mp4

### Where was the data currently stored in this dataset sourced from
Other

### If you answered "Other" in the previous question, enter the details here
douyu's own storage device

### If you are a data preparer. What is your location (Country/Region)
China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
a custom tool based on https://github.com/tech-greedy/generate-car

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
never seen

### Please share a sample of the data
https://pan.baidu.com/s/10NSl2cLY6QWwA0y5YruMBg?pwd=nqqg

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Confirm

### What is the expected retrieval frequency for this data
Sporadic

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers
HTTP or FTP server, Shipping hard drives

### How did you find your storage providers
Partners

### Please list the provider IDs and location of the storage providers you will be working with.
f03224629
f03224641
f03224713
f03224722
f03224727
其他待定

### How do you plan to make deals to your storage providers
Boost client

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by willscott** [comment]
1. Douyu streaming content is copyright protected. Do you have permission from Douyu to be archiving their content?

2. The provided sample does not actually help us understand what content is to be saved to filecoin. We need a full accounting of the proposed dataset. if the dataset is indeed public, this should be possible.

**Comment by dengxy-111** [comment]
&nbsp;Douyu Video’s data is publicly accessible at https://v.douyu.com/, and we are also contacting for authorization




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fidlabs/Open-Data-Pathway"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月29日(星期二) 上午9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fidlabs/Open-Data-Pathway] [DataCap Application] <  武汉斗鱼网络科技有限公司 &gt; <2024-10-29T01:34:28.057Z&gt; (Issue #95)





  
 
Douyu streaming content is copyright protected. Do you have permission from Douyu to be archiving their content?
 
 
 
The provided sample does not actually help us understand what content is to be saved to filecoin. We need a full accounting of the proposed dataset. if the dataset is indeed public, this should be possible.

**Comment by martplo** [comment]
@dengxy-111 
What do you mean by that?
>Is this project associated with other projects/ecosystem stakeholders?
No

>If answered yes, what are the other projects/ecosystem stakeholders
mp4

What's the mp4 here?


Also, SPs you've provided do not support spark and do not have a given location. Could you provide SPs that support spark and are in at least 3 geographic locations?

Please refer to our policy on preparing data: https://github.com/fidlabs/Open-Data-Pathway/wiki/Policies

**Comment by dengxy-111** [comment]
Hi, thank you for your email.


    Regarding the issue you mentioned, here is my response:


     mp4 is the answer to “Describe the data being stored onto Filecoin”, which is the next question of “If answered yes, what are the other projects/ecosystem stakeholders”. It is unclear what happened that caused the answers to be out of order.
       The currently listed SPs are newly generated and are ready for sealing. They currently have no power and their geographical locations cannot be determined immediately, but we will abide by the rules and distribute them in multiple cities. The following three SPs which provided by partners are old nodes that may be sealing future: f02013352 (Hong Kong, China), f02035256 (Ya'an, Sichuan, China), and f01999672 (Mianyang, Sichuan, China)






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fidlabs/Open-Data-Pathway"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月29日(星期二) 晚上10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fidlabs/Open-Data-Pathway] [DataCap Application] <  武汉斗鱼网络科技有限公司 &gt; <2024-10-29T01:34:28.057Z&gt; (Issue #95)





 
@dengxy-111
 What do you mean by that?
  
Is this project associated with other projects/ecosystem stakeholders?
 No
   
If answered yes, what are the other projects/ecosystem stakeholders
 mp4
  
What's the mp4 here?
 
Also, SPs you've provided do not support spark and do not have a given location. Could you provide SPs that support spark and are in at least 3 geographic locations?
 
Please refer to our policy on preparing data: https://github.com/fidlabs/Open-Data-Pathway/wiki/Policies

**Comment by martplo** [comment]
@dengxy-111 Those SPs have bad retrieval and are in the same region. 

>They currently have no power and their geographical locations cannot be determined immediately, but we will abide by the rules and distribute them in multiple cities.

You can ask them for geographical confirmations. 

>Douyu Video’s data is publicly accessible at https://v.douyu.com/, and we are also contacting for authorization

I'd like to see the authorization from them, before we'll agree to give you any DC.

**Comment by dengxy-111** [comment]
Hello,&nbsp;


Through the current work I feel that it will be difficult to delegate, if there is progress will be contacted.&nbsp;


Thanks for checking it out.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fidlabs/Open-Data-Pathway"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月30日(星期三) 晚上9:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fidlabs/Open-Data-Pathway] [DataCap Application] <  武汉斗鱼网络科技有限公司 &gt; <2024-10-29T01:34:28.057Z&gt; (Issue #95)





 
@dengxy-111 Those SPs have bad retrieval and are in the same region.
  
They currently have no power and their geographical locations cannot be determined immediately, but we will abide by the rules and distribute them in multiple cities.
  
You can ask them for geographical confirmations.
  
Douyu Video’s data is publicly accessible at https://v.douyu.com/, and we are also contacting for authorization
  
I'd like to see the authorization from them, before we'll agree to give you any DC.
